services:
  # SERVER
  backend:
    build:
      context: .
      target: dev
    environment:
      PORT: 8080
      WWW_DIR: /srv/www
    ports:
      - 8080:8080
    volumes:
      - .:/root/app
    working_dir: /root/app
