services:
  # REVERSE PROXY
  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # SERVER
  backend:
    build:
      context: ./
      target: backend-dev
    environment:
      PORT: 8080
      WWW_DIR: /srv/www
    develop:
      watch:
        - path: ./src
          action: sync
          target: /root/app/src
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 8080
